<?php


if(isset($_REQUEST['rep']) && !empty($_REQUEST['rep']) )
{
    if($_REQUEST['rep'] == 'order'){

        $tempdata = $objReport->showAllOrders();

        foreach($tempdata as $temp)
        {
            $datas[] = array('Order Name'=>$temp['quote_name'],'Amount'=>$temp['amount'],'Quantity'=>$temp['quantity'],'Order generated by'=>$temp['order_user'],'Supplier'=>$temp['bid_user'],'Order Date'=>$temp['date_added'] );
        }
        $obj = new ITFExport($datas);
        $obj->download();
    } elseif ($_REQUEST['rep'] == 'transaction') {
        $tempdata = $objReport->showAllTransactions();

        foreach($tempdata as $temp)
        {
            $datas[] = array('Order Name'=>$temp['quote_name'],'Payment Amount'=>$temp['payment_amount'],'Quantity'=>$temp['num_cart_items'],'Payment User'=>$temp['order_user'],'Payer Email'=>$temp['payer_email'],'Transaction Id'=>$temp['txn_id'],'Currency'=>$temp['mc_currency'],'Payment Date'=>$temp['date_added'],'Order Date'=>$temp['order_date'],'IPN Track ID'=>$temp['ipn_track_id'],'Payment Status'=>$temp['payment_status'] );
        }
        $obj = new ITFExport($datas);
        $obj->download();
    }

}else{
    flash('Something went wrong !','2');

}
?>
